// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmcx5hxvtsQhW-yjOsM-NTRjnxzm9LjTo',
    appId: '1:932320383811:web:970994230f503d0eaa15f6',
    messagingSenderId: '932320383811',
    projectId: 'test-chat-d37ac',
    authDomain: 'test-chat-d37ac.firebaseapp.com',
    storageBucket: 'test-chat-d37ac.appspot.com',
    measurementId: 'G-P4F59N35EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB64BEb3_ma3ImM-bqrUiD8x4b05gOZWDs',
    appId: '1:932320383811:android:fabb2a485ec02248aa15f6',
    messagingSenderId: '932320383811',
    projectId: 'test-chat-d37ac',
    storageBucket: 'test-chat-d37ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWgeaM_rJtw9cmhmzCOoHJP-9RuGoY87o',
    appId: '1:932320383811:ios:fb8f3c1c8da7004baa15f6',
    messagingSenderId: '932320383811',
    projectId: 'test-chat-d37ac',
    storageBucket: 'test-chat-d37ac.appspot.com',
    iosClientId: '932320383811-9mg2i2sfnddd6rns15v11st3d3r5odn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitMarkot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWgeaM_rJtw9cmhmzCOoHJP-9RuGoY87o',
    appId: '1:932320383811:ios:fb8f3c1c8da7004baa15f6',
    messagingSenderId: '932320383811',
    projectId: 'test-chat-d37ac',
    storageBucket: 'test-chat-d37ac.appspot.com',
    iosClientId: '932320383811-9mg2i2sfnddd6rns15v11st3d3r5odn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitMarkot',
  );
}
